### ISSUE TITLE
java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationV(Ljava/lang/Object;)Lscalaz/syntax/ValidationV;

### ISSUE THREAD

**Issue by jagatsingh** [typesafehub/sbteclipse#221]
Hi,

You will get the below error if we dont keep plugins.sbt in correct place.

Documenting for helping others not to waste time.

Eclipse 4.4
```
java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationV(Ljava/lang/Object;)Lscalaz/syntax/ValidationV;
```

Added the required plugin settings in 

/.sbt/0.13/plugins/plugins.sbt

full log is below.
```
[info] About to create Eclipse project files for your project(s).
java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationV(Ljava/lang/Object;)Lscalaz/syntax/ValidationV;
        at com.typesafe.sbteclipse.core.package$.setting(package.scala:66)
        at com.typesafe.sbteclipse.core.Eclipse$.skipParents(Eclipse.scala:495)
        at com.typesafe.sbteclipse.core.Eclipse$$anonfun$action$1.apply$mcZ$sp(Eclipse.scala:103)
        at com.typesafe.sbteclipse.core.Eclipse$$anonfun$action$1.apply(Eclipse.scala:103)
        at com.typesafe.sbteclipse.core.Eclipse$$anonfun$action$1.apply(Eclipse.scala:103)
        at scala.Option.getOrElse(Option.scala:120)
        at com.typesafe.sbteclipse.core.Eclipse$.action(Eclipse.scala:103)
        at com.typesafe.sbteclipse.core.Eclipse$$anonfun$eclipseCommand$2.apply(Eclipse.scala:82)
        at com.typesafe.sbteclipse.core.Eclipse$$anonfun$eclipseCommand$2.apply(Eclipse.scala:82)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
        at sbt.Command$.process(Command.scala:95)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:87)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:87)
        at sbt.State$$anon$1.process(State.scala:176)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:87)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:87)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.MainLoop$.next(MainLoop.scala:87)
        at sbt.MainLoop$.run(MainLoop.scala:80)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:69)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
        at sbt.Using.apply(Using.scala:25)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
        at sbt.MainLoop$.runLogged(MainLoop.scala:25)
        at sbt.xMain.run(Main.scala:26)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:19)
        at xsbt.boot.Boot$.runImpl(Boot.scala:44)
        at xsbt.boot.Boot$.main(Boot.scala:20)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationV(Ljava/lang/Object;)Lscalaz/syntax/ValidationV;

```

**Comment by benmccann** [comment]
Can you try with sbteclipse 4.0.0-RC1?

**Comment by fellz** [comment]
@benmccann got this bug when used sbteclipse plugin 4.0.0-RC1

here is complete plugins.sbt

```
resolvers += "Typesafe repository" at "https://repo.typesafe.com/typesafe/releases/"

// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.8")

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0-RC1")

// web plugins

addSbtPlugin("com.typesafe.sbt" % "sbt-coffeescript" % "1.0.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.0.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.1")

addSbtPlugin("com.typesafe.sbt" % "sbt-rjs" % "1.0.1")

addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.0.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.0.0")
```
 myapp/project/plugins.sbt
sbt 0.13.8
myapp was made via ``` activator new myapp ```

**Comment by benmccann** [comment]
sbteclipse 4.0.0 won't work with Play 2.3 unfortunately. You can try with Play 2.4-M3

**Comment by zakpatterson** [comment]
Getting the same error with sbt-eclipse 4.0.0-RC1 and Play 2.4.0-M3

**Comment by benmccann** [comment]
Oh, I know what this is now. I was confused at first and thought it was something else. This will be fixed in Play 2.4-RC1, which should be released any day now. I'm going to close this issue since it's already been fixed in Play.

**Comment by rashmitk** [comment]
I was referencing sbteclipse version 4.0.0 which was giving this exception, However I could able to fix this issue by updating my sbteclipse version from 4.0.0 to 3.0.0 in my global plugin.sbt file.

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "3.0.0")

**Comment by vito-c** [comment]
I get this error with version 2.5.0, 3.0.0 and 4.0.0 @benmccann is there another version I can try?

**Comment by benmccann** [comment]
I think this error was conflicting versions of scalaz? You must be pulling in another version somewhere else in your project

**Comment by vito-c** [comment]
is there a version of sbteclipse compatible with "org.scalaz" %% "scalaz-core" % "7.1.2"?

**Comment by vito-c** [comment]
@benmccann we are using `scalaz-core 7.1.2` and sbteclipse is using `7.1.0` shouldn't these two version be compatible? 

I tried bumping my version of sbteclipse and then that wasn't compatible with sbt-play 2.3.9 I tried bumping my play to 2.4.0 and there was errors. I will try 3.0.0 later :(

**Comment by oswaldo** [comment]
Just in case someone hits this one again, it might be triggered by other enabled plugins. In my case, the issue/conflict with version 3.0.0 is triggered by `~/.sbt/0.13/plugins/coursier.sbt` with `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M12")`

**Comment by durban** [comment]
And there is a similar issue with version 4.0.0 and coursier 1.0.0-M14 (due to alexarchambault/coursier/pull/328).
